D1_metabat_output.10.fa.emapper.gff
10
[E::hts_open_format] Failed to open file "/D3_metabat_output.10.fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output.10.fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
D1_metabat_output.11.fa.emapper.gff
11
[E::hts_open_format] Failed to open file "/D3_metabat_output.11.fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output.11.fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
D1_metabat_output.12.fa.emapper.gff
12
[E::hts_open_format] Failed to open file "/D3_metabat_output.12.fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output.12.fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
D1_metabat_output.1.fa.emapper.gff
1
[E::hts_open_format] Failed to open file "/D3_metabat_output.1.fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output.1.fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
D1_metabat_output.2.fa.emapper.gff
2
[E::hts_open_format] Failed to open file "/D3_metabat_output.2.fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output.2.fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
D1_metabat_output.3.fa.emapper.gff
3
[E::hts_open_format] Failed to open file "/D3_metabat_output.3.fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output.3.fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
D1_metabat_output.4.fa.emapper.gff
4
[E::hts_open_format] Failed to open file "/D3_metabat_output.4.fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output.4.fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
D1_metabat_output.5.fa.emapper.gff
5
[E::hts_open_format] Failed to open file "/D3_metabat_output.5.fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output.5.fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
D1_metabat_output.6.fa.emapper.gff
6
[E::hts_open_format] Failed to open file "/D3_metabat_output.6.fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output.6.fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
D1_metabat_output.7.fa.emapper.gff
7
[E::hts_open_format] Failed to open file "/D3_metabat_output.7.fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output.7.fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
D1_metabat_output.8.fa.emapper.gff
8
[E::hts_open_format] Failed to open file "/D3_metabat_output.8.fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output.8.fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
D1_metabat_output.9.fa.emapper.gff
9
[E::hts_open_format] Failed to open file "/D3_metabat_output.9.fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output.9.fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
